export const LOGIN_REQUESTED  = 'LOGIN_REQUESTED'
export const LOGIN_COMPLETED  = 'LOGIN_COMPLETED'
export const LOGIN_FAILED     = 'LOGIN_FAILED'

export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED'
export const LOGOUT_COMPLETED = 'LOGOUT_COMPLETED'
export const LOGOUT_FAILED    = 'LOGOUT_FAILED'
